version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/vuln.db
      - PORT=8080
    volumes:
      - ./data:/data
    command: >
      sh -c "swag init -g main.go &&
             go run main.go"

volumes:
  data: 