openapi: 3.0.0
info:
  title: Vulnerable REST API
  description: |
    A deliberately vulnerable REST API for educational and security testing purposes.
    This API implements various security vulnerabilities as defined in the OWASP Benchmark.
  version: 1.0.0
  contact:
    name: April Conger
    url: https://github.com/azconger/vuln-rest-api

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token obtained from /auth/login or /auth/token endpoints.
        The implementation is intentionally vulnerable.

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: integer
          description: HTTP status code

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: user
        password:
          type: string
          example: password

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: JWT access token
        refresh_token:
          type: string
          description: JWT refresh token
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          description: Token expiration in seconds

paths:
  /auth/login:
    post:
      summary: Login with username and password
      description: |
        Authenticate user and return JWT tokens.
        This endpoint is intentionally vulnerable to various attacks.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/token:
    post:
      summary: OAuth 2.0 ROPC token endpoint
      description: |
        OAuth 2.0 Resource Owner Password Credentials flow.
        This endpoint is intentionally vulnerable to various attacks.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - grant_type
                - username
                - password
              properties:
                grant_type:
                  type: string
                  example: password
                username:
                  type: string
                  example: user
                password:
                  type: string
                  example: password
      responses:
        '200':
          description: Successful token generation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      summary: List users
      description: |
        Retrieve a list of users.
        This endpoint is vulnerable to SQL injection.
      tags:
        - Users
      security:
        - BearerAuth: []
      parameters:
        - name: search
          in: query
          description: Search query (vulnerable to SQL injection)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of users
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /commands:
    post:
      summary: Execute command
      description: |
        Execute a system command.
        This endpoint is vulnerable to command injection.
      tags:
        - Commands
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - command
              properties:
                command:
                  type: string
                  description: Command to execute (vulnerable to command injection)
      responses:
        '200':
          description: Command executed successfully
        '401':
          description: Unauthorized
        '400':
          description: Invalid command

  /files:
    get:
      summary: Get file contents
      description: |
        Retrieve contents of a file.
        This endpoint is vulnerable to path traversal.
      tags:
        - Files
      security:
        - BearerAuth: []
      parameters:
        - name: path
          in: query
          description: File path (vulnerable to path traversal)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File contents
        '401':
          description: Unauthorized
        '404':
          description: File not found

security:
  - BearerAuth: [] 